version: '3.8'
services:
  strapi:
    container_name: strapi
    image: dunadigital/strapi:latest
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      JWT_SECRET: example
    ports:
      - "1337:1337"
  postgres:
    container_name: postgres
    image: postgres:14.2
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi